// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackOverflow.Models;

namespace StackOverflow.Migrations
{
    [DbContext(typeof(StackOverflowContext))]
    partial class StackOverflowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StackOverflow.Models.Problema", b =>
                {
                    b.Property<int>("ProblemaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo");

                    b.HasKey("ProblemaId");

                    b.ToTable("Problemas");
                });

            modelBuilder.Entity("StackOverflow.Models.Solucao", b =>
                {
                    b.Property<int>("SolucaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<int>("ProblemaId");

                    b.Property<int>("Votos");

                    b.HasKey("SolucaoId");

                    b.HasIndex("ProblemaId");

                    b.ToTable("Solucoes");
                });

            modelBuilder.Entity("StackOverflow.Models.Solucao", b =>
                {
                    b.HasOne("StackOverflow.Models.Problema", "Problema")
                        .WithMany("Solucoes")
                        .HasForeignKey("ProblemaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
